<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#" lang="id">
<head>
    <!-- Developing by Ahmad Navis Zarkasy (TOS IT Development) -->
    

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="google-site-verification" content="VQ9ilUnTK8dVHuJ5jffz4Wfs76-X9YdT6kLFfenHsYQ" />
    <title>TOS Adventure Provider Rafting Outbound di Pacet Mojokerto</title>
    <meta name="description" content="TOS Adventure adalah provider yang bergerak dibidang rafting pacet, outbound pacet, paintball pacet dan wisata adventure di Pacet Mojokerto" />
    <meta name="keywords" content="rafting pacet, outbound pacet, rafting mojokerto, outbound mojokerto, wisata pacet"/>
    <meta name="robots" content="index, follow">
    <meta name="googlebot" content="index, follow">
    <meta name="language" content="indonesia">

    <meta property="og:type" content="website" />
    <meta property="og:title" content="TOS Adventure Provider Rafting Outbound di Pacet Mojokerto" />
    <meta property="og:description" content="TOS Adventure adalah provider yang bergerak dibidang rafting pacet, outbound pacet, paintball pacet dan wisata adventure di Pacet Mojokerto">
    <meta property="og:url" content="https://www.tosraftingpacet.com/" />
    <meta property="og:site_name" content="TOS ADVENTURE Provider Rafting Pacet & Outbound Pacet">
    <meta property="og:image" content="https://www.tosraftingpacet.com/img/raf2.jpg">
    <meta property="og:image:secure_url" content="https://www.tosraftingpacet.com/img/raf2.jpg">
    <meta property="og:image:width" content="850">
    <meta property="og:image:height" content="450">
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:alt" content="TOS Rafting Pacet">


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="canonical" href="https://www.tosraftingpacet.com/" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <link rel="shortcut icon" type="image/png" href="img/new_tos.png"/>

    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
        <script type="application/ld+json">
        {"@context":"http://schema.org","@type":"LocalBusiness","name":"TOS ADVENTURE PACET","image":["https://www.tosraftingpacet.com/img/raf4-min.jpg","https://www.tosraftingpacet.com/img/out2.jpg","https://www.tosraftingpacet.com/img/pain2.jpg"],"priceRange":"Mulai Rp. 150.000,-","telephone":"082231372191","url":"https://www.tosraftingpacet.com/","email":"pacetraftingtos@gmail.com","address":{"@type":"PostalAddress","streetAddress":"Wana Wisata Air Panas Pacet Mojokerto","addressLocality":"Mojokerto","addressRegion":"Jawa Timur","addressCountry":"Indonesia"}}
        </script>
    
</head>
<body>
    <!-- header -->
    <header id="myHeader-home">
    <nav>
        <a href="TOS-Adventure-Pacet" id="logo"><img src="img/new_tos333.png" alt="logo tos adventure pacet"></a>
        <span class="open-menu">
            <button onclick="openSlideMenu()" >
                <svg width="30" height="30">
                    <path d="M0,5 30,5" stroke="#fff" stroke-width="5"/>
                    <path d="M0,14 30,14" stroke="#fff" stroke-width="5"/>
                    <path d="M0,23 30,23" stroke="#fff" stroke-width="5"/>
                </svg> <p>Menu</p>
            </button>
        </span>
        <ul>
            <li><a href="TOS-Adventure-Pacet">Home</a></li>
            <li><a href="tos-rafting-Pacet">Rafting</a></li>
            <li class="dropdown"><a href="#" class="not-active">Outbound <span class="fa fa-chevron-down"></span> </a>
                <div class="dropdown-content">
                <a href="tos-fun-outbound-Pacet">Fun Outbound Outing</a>
                <a href="tos-fun-adventure-outbound-Pacet">Fun Outbound Adventure</a>
                <a href="tos-outbound-motivasi-Pacet">Outbound Motivasi</a>
                <!-- <a href="Harga-paket-outbound-Pacet-Mojokerto">Outbound Full Training</a> -->
                <a href="tos-family-gathering-Pacet">Family Gathering</a>
                <!-- <a href="Harga-paket-outbound-Pacet-Mojokerto">Outbound Edukasi</a> -->
                </div>
            </li>
            <li class="dropdown"><a href="#" class="not-active">Paket Lain <span class="fa fa-chevron-down"></span></a>
                <div class="dropdown-content">
                <a href="tos-paintball-Pacet">Paintball War</a>
                <a href="info-travel-&-outing">Travel Partner</a>
                <a href="info-event-organizer">Event Organizer</a>
                </div>
            </li>
            <li class="dropdown"><a href="#" class="not-active">Villa <span class="fa fa-chevron-down"></span></a>
                <div class="dropdown-content">
                <a href="sewa-villa-Pacet">Sewa Villa Pacet</a>
                <!-- <a href="Harga-sewa-villa-murah-di-Trawas-Mojokerto">Villa Trawas</a> -->
                <!-- <a href="#client">Camping Santai</a> -->
                </div>
            </li>
            <li class="dropdown"><a href="#" class="not-active">Info Lain <span class="fa fa-chevron-down"></span></a>
                <div class="dropdown-content">
                <a href="tentang-TOS-Adventure-Pacet">Tentang Kami</a>
                <a href="Jurnal-klien-TOS-Adventure-Pacet">Jurnal Klien</a>
                <!-- <a href="#client">Berita & Artikel</a> -->
                <a href="#contact">Galeri TOS</a>
                </div>
            </li>
            <li><a href="kontak-dan-reservasi">Contact</a></li>
        </ul>
    </nav>
    </header>

    <div id="mobile-menu" class="side-menu">
        <button class="btn-close" onclick="closeSlideMenu()">&times;</button>
        <a href="tos-rafting-Pacet">Tos Rafting Pacet</a>
        <a href="tos-fun-outbound-Pacet">Fun Outing Outbound Pacet</a>
        <a href="tos-fun-adventure-outbound-Pacet">Fun Adventure Outbound Pacet</a>
        <a href="tos-outbound-motivasi-Pacet">Outbound Motivasi</a>
        <a href="tos-family-gathering-Pacet">Family Gathering</a>
        <a href="tos-paintball-Pacet">TOS Paintball Pacet</a>
        <a href="info-travel-&-outing">Travel Partner</a>
        <a href="info-event-organizer">Event Organizer</a>
        <a href="Harga-sewa-villa-Pacet">Sewa Villa Pacet</a>
        <a href="tentang-TOS-Adventure-Pacet">Tentang Kami</a>
        <a href="Jurnal-klien-TOS-Adventure-Pacet">Jurnal Klien</a>
        <a href="kontak-dan-reservasi">Contact</a>
    </div>
    <!-- end header -->
    
    <!-- banner -->
    <section id="banner">
        <div class="container">
            <h1>Feel The Nature Enjoy The Flow</h1>
            <p>Selamat Datang di TOS ADVENTURE PACET, Nikmati Sensasi keseruan ber adventure di ALAM</p>
            <p class="p2">Ingin Menghemat waktu anda? klik dua tombol dibawah ini!!</p>
            <a href="/pricelist.pdf" class="btn-biru" download="Pricelist Paket TOS Adventure Pacet">Download Pricelist disini</a>
            <a href="https://wa.me/6282231372191" target="_blank" class="btn-utama">Reservasi Sekarang!</a>
        </div>
    </section>
    <!-- end banner -->

    <!-- box -->
    <section id="boxes">
    <h2>Tentang TOS Adventure Pacet</h2>
    <div class="line"><img src="img/line.png" alt="garis batas"></div>
    <p>Tos Adventure Pacet adalah provider wisata yang berada di kawasan Wana Wisata Air Panas Padusan Pacet Mojokerto Jawa Timur, bergerak di bidang wisata adventure, rafting pacet, outbound pacet, paintball pacet, travel partner, event organizer dan program edukasi dengan produk andalan kami TOS RAFTING PACET. Berpengalaman selama lebih dari 10 tahun semenjak berdiri tahun 2008, TOS Adventure Pacet siap memberi pelayanan terbaik untuk anda
    </p>
        <div class="container">
            <div class="box">
                <span class="fa fa-thumbs-o-up circle-icon"></span>
                <h3>PELAYANAN EKSTRA</h3> 
                <p>Kepuasan dan kesenangan anda adalah tujuan kami yang paling utama, maka kami pastikan memberi pelayanan maksimal dan terbaik hanya untuk anda.
                </p>
            </div>
            <div class="box">
                <span class="fa fa-user-secret circle-icon"></span>
                <h3>TEAM PROFESIONAL</h3> 
                <p>Kami memiliki team profesional yang siap mendampingi anda mulai dari rafting guide, outbound trainer dan travel guide yang semua sudah bersertifikat BNSP nasional.
                </p>
            </div>
            <div class="box">
                <span class="fa fa fa-id-card circle-icon"></span>
                <h3>PENUH PENGALAMAN</h3> 
                <p>Lebih dari 10 tahun telah banyak klien dari seluruh Indonesia yang mempercayakan kegiatan rafting, outbound maupun outing mereka bersama kami.
                </p>
            </div>
            <div class="box">
                <span class="fa fa-space-shuttle circle-icon"></span>
                <h3>LOKASI STRATEGIS</h3> 
                <p>Kami sebagai salah satu opsi wisata pacet berada di kawasan Wana Wisata Air Panas Padusan Pacet Mojokerto  yang memiliki banyak spot wisata untuk dikunjungi.
                </p>
            </div>

        </div> 
    </section>
    <!-- end box -->

    <!-- Product -->
    <section id="product">
        <h1>
            Paket Tos Adventure Pacet
        </h1>
        <div class="line"><img src="img/line.png" alt="garis batas"></div>
        <div class="container">
            <div class="box">
                <img src="img/raf4-min.jpg" alt="paket rafting pacet">
                <h2><strong>Paket Tos Rafting Pacet</strong> </h2> 
                <p>*mulai harga :</p>
                <p>RP. 150.000,-/ORANG</p>
                <button onclick="window.location.href='tos-rafting-Pacet'"> <strong>Selengkapnya</strong> </button>
            </div>
            <div class="box">
                <img src="img/out2.jpg" alt="paket outbound pacet">
                <h2>Paket Tos Outbound Pacet</h2> 
                <p>*mulai harga :</p>
                <p>RP. 175.000,-/ORANG</p>
                <button onclick="window.location.href='tos-outbound-Pacet'"><strong>Selengkapnya</strong></button>
            </div>
            <div class="box">
                <img src="img/pain2.jpg" alt="paket paintball pacet">
                <h2>Paket Tos Paintball Pacet</h2> 
                <p>*mulai harga :</p>
                <p>RP. 150.000,-/ORANG</p>
                <button onclick="window.location.href='tos-paintball-Pacet'"><strong>Selengkapnya</strong></button>
            </div>
            <div class="box">
                <img src="img/camp1.jpg" alt="info paket lain">
                <h2>Paket Tos Adventure lain</h2> 
                <p>*mulai harga :</p>
                <p>KONTAK UNTUK HARGA</p>
                <button  onclick="window.location.href='#contact'"><strong>Selengkapnya</strong></button>
            </div>
        </div>
    </section>

    <!-- end product -->

    <!-- client -->
    <section id="client">
        <div class="container">
            <h2>Anda Membutuhkan Akomodasi Villa, Homestay atau area Camping?</h2>
            <p>Kami siap menyediakan info dan penawaran villa, homestay maupun area camping beserta alatnya disekitar area Pacet atau Trawas sesuai kebutuhan anda. Langsung hubungi kami untuk detailnya.</p>
            <button class="btn-segar" onclick="window.location.href='sewa-villa-Pacet'"> <strong>Selengkapnya</strong> </button>
            <button onclick="window.location.href='#contact'"> <strong>Hubungi Kami</strong> </button>
        </div>
    </section>

    <!-- end client -->

    <!-- shop section -->
    <section id="shop">
        <h2>TOS Souvenir</h2>
        <div class="line"><img src="img/line.png" alt="garis batas"></div>
        <p>TOS Souvenir menyediakan berbagai macam souvenir untuk anda bawa pulang sebagai kenang - kenangan dan hadiah bagi keluarga dan saudara di Rumah</p>
        <div class="container">
            <button onclick="window.location.href='TOS-Adventure-Pacet'">Cek Sekarang</button>
        </div>
    </section>
    <!-- end shop -->

    <!-- tamu -->
    <section id="tamu">
    <h2>Jurnal Kegiatan Klien</h2>
    <div class="line"><img src="img/line.png" alt="garis batas"></div>
    <p>Tos Adventure Pacet sudah bekerjasama dan melayani berbagai klien dari seluruh Indonesia baik mulai dari Perusahaan, instansi Pemerintah, sekolah, universitas, organisasi, club, komunitas keluarga, maupun umum. Intip sekilas bagaimana perjalanan dan kegiatan para klien kami</p>
        <div class="container">
            <div class="box">
                <img src="img/banner.jpg" alt="kegiatan rafting outbound shopee.id">
                <h3>Serunya outbound & rafting Pacet Seller Gathering Shopee.id</h3> 
                <p>Shopee.id bersama para Seller di area Jawa Timur melakukan gathering pertama mereka di TOS Adventure Pacet. Memilih lokasi di Mojokerto, TOS Adventure Pacet yang merupakan provider rafting mojokerto dan outbound mojokerto dipercaya untuk menghandle gathering Seller ini. Diawali dengan kegiatan fun outing outbound pacet yang penuh keceriaan. Para Seller yang sebagian baru bertemu ini melanjutkan keseruan kegiatan gathering dengan menantang adrenalin mereka, dalam kegiatan rafting pacet yang menantang. Walaupun Trip Rafting Pacet yang diambil adalah Trip Rafting welirang yang paling pendek, tetapi tidak mengurangi keseruan kebersamaan mereka. Have fun dan terima kasih atas kunjungannya.
                </p>
            </div>
            <div class="box">
                <img src="img/out3.jpg" alt="kegiatan rafting outbound KPPBC Surabaya">
                <h3>Seru serta berkesannya kegiatan Capacity Building KPPBC Surabaya</h3> 
                <p>Kegiatan Capacity Building 2 hari 1 malam oleh KPPBC Surabaya bersama TOS Adventure Pacet ini berlangsung seru dan penuh makna. Diawali dengan kegiatan fun outbound pacet yang sangat meriah, kini giliran mereka melewati salah satu tantangan trip rafting pacet terbaik yaitu arjuna trip rafting dengan penuh keseruan. Malamnya kegiatan outbound motivasi bersinergi dengan Royal Camp Trawas dilanjutkan api unggun, electone dan Nobar Piala Dunia. Kemudian pagi keesokan harinya kegiatan senam dan hash, ditutup dengan pembagian doorprize. Kegiatan yang sangat berkesan, terima kasih telah mempercayakan kegiatan Capacity Building Bersama TOS Adventure Pacet.
                </p>
            </div>
            <div class="box">
                <img src="img/raf2.jpg" alt="kegiatan rafting CCRC Bank BTN Surabaya">
                <h3>Lepas penat dengan rafting pacet bersama CCRC Bank BTN Surabaya</h3> 
                <p>Melepaskan sedikit penatnya pekerjaan, para rekan-rekan Unit CCRC Bank BTN cabang Surabaya memilih liburan mereka dengan menikmati keseruan Trip Rafting Pacet teratas TOS Adventure Pacet yaitu Mahameru Trip Rafting yang jalurnya memacu andrenalin dengan balutan dengan keindahan alam natural disepanjang perjalanan. Ditutup dengan makan bersama dan menikmati hiburan music electone yang penuh keakraban. Semoga penat kerja rekan-rekan bisa hilang setelah menikmati serunya rafting pacet dan terima kasih telah mengunjungi kami.
                </p>
            </div>
        </div>
        <div class="selengkapnya-journey">
        <button onclick="window.location.href='Jurnal-klien-TOS-Adventure-Pacet'">Lihat Semua Jurnal Klien Disini</button>
        </div>
        
    </section>
    <!-- end tamu -->

    <!-- Contact -->
    <?php include "detail_kontak.php" ?>
    <!-- end Contact -->

    <!-- footer -->
    <?php include "footer.php" ?>
    <!-- end footer -->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-75178696-2" defer></script>
        <script defer>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-75178696-2');
        </script>

<script>
    window.onscroll = function() {myFunction()};

    var header = document.getElementById("myHeader-home");
    var sticky = header.offsetTop;
    

    function myFunction() {
    if (window.pageYOffset > sticky) {
        header.classList.add("sticky");
        
    } else {
        header.classList.remove("sticky");
        
    }
    }

    function openSlideMenu(){
        document.getElementById("mobile-menu").style.width = '250px';
    }

    function closeSlideMenu(){
        document.getElementById("mobile-menu").style.width = '0';
    }
</script>

</body>
</html>