<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#" lang="id">
<head>
    <!-- Developing by Ahmad Navis Zarkasy (TOS IT Development) -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Harga Paket Trip Rafting Pacet di TOS ADVENTURE Pacet Mojokerto</title>
    <meta name="description" content="Nikmati 3 TRIP RAFTING PACET andalan dari TOS Rafting Pacet di sungai kromong dengan sensasi sungai pengunungan Welirang Pacet, Mojokerto" />
    <meta name="keywords" content="rafting pacet, outbound pacet, rafting mojokerto, outbound mojokerto, wisata pacet"/>
    <meta name="robots" content="index, follow">
    <meta name="googlebot" content="index, follow">
    <meta name="language" content="indonesia">

    <meta property="og:type" content="website" />
    <meta property="og:title" content="TOS Adventure Provider Rafting Outbound di Pacet Mojokerto" />
    <meta property="og:description" content="TOS Adventure adalah provider yang bergerak dibidang rafting pacet, outbound pacet, paintball pacet dan wisata adventure di Pacet Mojokerto">
    <meta property="og:url" content="https://www.tosraftingpacet.com/" />
    <meta property="og:site_name" content="TOS ADVENTURE Provider Rafting Pacet & Outbound Pacet">
    <meta property="og:image" content="https://www.tosraftingpacet.com/img/raf2.jpg">
    <meta property="og:image:secure_url" content="https://www.tosraftingpacet.com/img/raf2.jpg">
    <meta property="og:image:width" content="850">
    <meta property="og:image:height" content="450">
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:alt" content="TOS Rafting Pacet">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <link rel="shortcut icon" type="image/png" href="img/new_tos.png"/>

    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
        {"@context":"http://schema.org","@type":"LocalBusiness","name":"TOS ADVENTURE PACET","image":["https://www.tosraftingpacet.com/img/raf4-min.jpg","https://www.tosraftingpacet.com/img/out2.jpg","https://www.tosraftingpacet.com/img/pain2.jpg"],"priceRange":"Mulai Rp. 150.000,-","telephone":"082231372191","url":"https://www.tosraftingpacet.com/","email":"pacetraftingtos@gmail.com","address":{"@type":"PostalAddress","streetAddress":"Wana Wisata Air Panas Pacet Mojokerto","addressLocality":"Mojokerto","addressRegion":"Jawa Timur","addressCountry":"Indonesia"}}
        </script>
    
</head>
<body>
    <!-- header -->
    <?php include "header.php" ?>
    <!-- end header -->

    <!-- title halaman -->
    <section id="title-halaman">
        <div class="container">
            <h1>Detail Paket Trip Rafting Pacet</h1>
        </div>
    </section>
    <!-- end title halaman -->

    <!-- detail produk -->
    <section id="detail-produk">
        <div class="container">
        <div class="produk-umum">
                <div class="nama-produk">
                    <h2>Mahameru Trip Rafting Pacet</h2>
                    <p>Harga</p>
                    <h3>Rp. 250.000,- / Orang</h3>
                    <p>
                        <ul>
                            <li><a href="#informasi" class="btn-biru">Fasilitas & Ketentuan</a></li>
                            <li><a href="#contact" class="btn-utama">Reservasi Sekarang</a></li>
                        </ul>
                    </p>
                </div>
                <div class="keterangan-produk">
                    
                    <h3>Spesifikasi Trip Rafting :</h3>
                        <p>Durasi Arung : ± 3 jam</p>
                        <p>Jarak Arung : ± 10 km</p>
                        <p>Tingkat Kesulitan : 3-4 Grade</p>
                        <p>Jumlah Jeram : ± 90 jeram</p>
                    <h3>Deskripsi Trip Rafting :</h3>
                        <p>Mahameru trip rafting merupakan salah satu dari 3 trip rafting dari Tos Rafting Pacet yang memiliki grade paling tinggi. Trip Rafting ini cocok untuk anda yang benar-benar mencari sensasi petualangan yang ekstreme dan memacu adrenalin. Menyusuri sungai kromong atas  dibawah gunung welirang pacet dengan jeram-jeram ekstremenya, sambil menikmati indahnya pemandangan alam pegunungan pacet plus airnya yang jernih dan layak minum, tebing-tebing tinggi dibalut vegetasi yang masih natural serta karakter sungai hulu yang unik. Trip rafting Pacet teratas ini tentu akan sangat sayang untuk dilewatkan saat anda menikmati wisata pacet.
                        </p>
                </div>
            </div>
            <div class="produk-umum">
                <div class="nama-produk">
                    <h2>Arjuna Trip Rafting Pacet</h2>
                    <p>Harga</p>
                    <h3>Rp. 200.000,- / Orang</h3>
                    <p>
                        <ul>
                            <li><a href="#informasi" class="btn-biru">Fasilitas & Ketentuan</a></li>
                            <li><a href="#contact" class="btn-utama">Reservasi Sekarang</a></li>
                        </ul>
                    </p>
                </div>
                <div class="keterangan-produk">
                    
                    <h3>Spesifikasi Trip Rafting :</h3>
                        <p>Durasi Arung : ± 2 jam</p>
                        <p>Jarak Arung : ± 7 km</p>
                        <p>Tingkat Kesulitan : 2-3 Grade</p>
                        <p>Jumlah Jeram : ± 75 jeram</p>
                    <h3>Deskripsi Trip Rafting :</h3>
                        <p>Arjuno Trip Rafting merupakan BEST SELLER Trip Rafting di TOS Rafting Pacet. Dengan tingkat Grade tengahnya trip rafting ini sangat cocok untuk dijadikan referensi liburan adventure yang tetap seru tapi juga fun, untuk semua kalangan baik keluarga, perusahaan maupun bersama rekan-rekan. Indahnya alam liar pegunungan Welirang Pacet sepanjang jalur sungai kromong akan tetap anda rasakan bersama dengan segarnya air sungai hulu ini, maka bersiaplah untuk "ketagihan" menikmati serunya trip rafting Pacet kami yang satu ini.
                        </p>
                </div>
            </div>
            <div class="produk-umum">
                <div class="nama-produk">
                    <h2>Welirang Trip Rafting Pacet</h2>
                    <p>Harga</p>
                    <h3>Rp. 150.000,- / Orang</h3>
                    <p>
                        <ul>
                            <li><a href="#informasi" class="btn-biru">Fasilitas & Ketentuan</a></li>
                            <li><a href="#contact" class="btn-utama">Reservasi Sekarang</a></li>
                        </ul>
                    </p>     
                </div>
                <div class="keterangan-produk">
                    
                    <h3>Spesifikasi Trip Rafting :</h3>
                        <p>Durasi Arung : ± 1 jam</p>
                        <p>Jarak Arung : ± 5 km</p>
                        <p>Tingkat Kesulitan : 2-3 Grade</p>
                        <p>Jumlah Jeram : ± 30 jeram</p>
                    <h3>Deskripsi Trip Rafting :</h3>
                        <p>Welirang Trip Rafting ini merupakan Trip beginner dari Tos Rafting Pacet, bagi anda yang ingin sekedar melakukan trial atau ingin merasakan serunya rafting pacet dengan jeram-jeram funnya sungai kromong pacet untuk durasi yang singkat (go show). Cocok juga untuk melatih keberanian adik-adik kecil, karena trip rafting pacet satu ini aman untuk semua umur termasuk anak-anak. Trip Rafting Pacet Kami ini Tetap Fun dan seru dengan balutan alam pegunungan welirang, tentunya trip ini layak untuk anda coba sekarang sebagai pilihan wisata pacet ketika anda berlibur.
                        </p>
                </div>
            </div>  
            
        </div>
    </section>
    <!-- end detail produk -->

    <!-- fasilitas & syarat -->
    <section id="informasi">
        <h2>Fasilitas & Ketentuan</h2>
        <div class="line"><img src="img/line.png" alt="garis batas"></div>
        <div class="container">
                <div class="fasilitas">
                    <h3>Fasilitas Rafting Pacet</h3>
                    <p>Peralatan rafting lengkap</p>
                    <p>Profesional Rafting Guide & Rescue</p>
                    <p>Transportasi Lokal</p> 
                    <p>Safety Talk & Asuransi</p> 
                    <p>Welcome Drink & River Snack</p>
                    <p>Makan Prasmanan (KECUALI welirang trip)</p>
                    <p>Tiket Wanawisata Air Panas Pacet Mojokerto</p>
                    <p>Tiket Whirpool Berendam Air Panas Pacet (KECUALI welirang trip)</p>
                </div>
                <div class="emblem-tos">
                    <img src="img/new_tos11.png" alt="emblem tos adventure pacet">
                    <a href="#detail-produk" class="btn-utama">Lihat Trip Rafting Pacet</a>
                </div>
                <div class="ketentuan">
                    <h3>Syarat & Ketentuan Rafting Pacet</h3>
                    <p>Minimal Jumlah Peserta Rafting 6 ORANG<br>
                        (kurang dari 6 orang tetap dikenakan biaya untuk 6 orang)</p>
                    <p>Fix jumlah peserta Rafting H-2 pelaksanaan <br/>
                        jika ada pengurangan jumlah peserta di hari H kegiatan maka biaya tetap di charge sesuai jumlah peserta di booking awal</p>
                    <p>Harga paket rafting Pacet diatas BELUM termasuk Biaya DOKUMENTASI</p>
                    <p>DP paket Rafting Pacet Minimal 25%, maks. H-7 pelaksanaan kegiatan</p> 
                    <p>DP & Pelunasan paket Rafting Pacet Bisa Di Transfer ke :<br/>
                        Rek 610 513 5215 Bank BCA<br/>
                        A/N Ahmad Navis Zarkasy</p> 
                </div>
        </div>
    </section>
    <!-- end fasilitas & syarat -->

    <!-- produk lain -->
    <?php include "produk_lain.php"?>
    <!-- end produk lain -->

    <!-- Contact -->
    <?php include "detail_kontak.php" ?>
    <!-- end Contact -->

    <!-- footer -->
    <?php include "footer.php" ?>
    <!-- end footer -->

<script>
    window.onscroll = function() {myFunction()};

    var header = document.getElementById("myHeader");
    var sticky = header.offsetTop;
    

    function myFunction() {
    if (window.pageYOffset > sticky) {
        header.classList.add("sticky");
        
    } else {
        header.classList.remove("sticky");
        
    }
    }

    function openSlideMenu(){
        document.getElementById("mobile-menu").style.width = '250px';
    }

    function closeSlideMenu(){
        document.getElementById("mobile-menu").style.width = '0';
    }

    
</script>

</body>
</html>